# Generated by Django 4.2.1 on 2023-05-15 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('company_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('phone_num', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='CorporativeTrainingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Corporative Training',
                'verbose_name_plural': 'Corporative Trainings',
            },
        ),
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_banner', models.ImageField(blank=True, null=True, upload_to='imgfiles/')),
                ('about_content', models.CharField(blank=True, max_length=256, null=True)),
                ('vision', models.CharField(blank=True, max_length=256, null=True)),
                ('mission', models.CharField(blank=True, max_length=256, null=True)),
                ('values_context', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='ValuesImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imgfiles/')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='magali_app.settingsmodel')),
            ],
            options={
                'verbose_name': 'Values Image',
                'verbose_name_plural': 'Values Images',
            },
        ),
        migrations.CreateModel(
            name='CTCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('content', models.TextField(blank=True, null=True)),
                ('corporativetraining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctccategories', to='magali_app.corporativetrainingmodel')),
            ],
            options={
                'verbose_name': 'CTCategory',
                'verbose_name_plural': 'CTCategories',
            },
        ),
        migrations.CreateModel(
            name='CTCategoryImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_images', to='magali_app.ctcategorymodel')),
            ],
            options={
                'verbose_name': 'CTCategory Image',
                'verbose_name_plural': 'CTCategory Images',
            },
        ),
    ]
