# Generated by Django 4.2.1 on 2023-05-18 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magali_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('service_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='about_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valuesimagesmodel',
            name='image',
            field=models.ImageField(upload_to='values_imgfiles/'),
        ),
        migrations.AlterField(
            model_name='valuesimagesmodel',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_images', to='magali_app.settingsmodel'),
        ),
        migrations.CreateModel(
            name='ServicesImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_imgfiles/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_images', to='magali_app.servicesmodel')),
            ],
            options={
                'verbose_name': 'Service Image',
                'verbose_name_plural': 'Service Images',
            },
        ),
    ]
