# Generated by Django 4.2.1 on 2023-05-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magali_app', '0002_servicesmodel_alter_settingsmodel_about_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctcategoryimagesmodel',
            name='image',
            field=models.ImageField(default=2, upload_to='ctc_imgfiles/'),
            preserve_default=False,
        ),
    ]
