# Generated by Django 4.2.1 on 2023-05-24 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magali_app', '0003_ctcategoryimagesmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('content', models.TextField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='imgfiles/')),
            ],
            options={
                'verbose_name': 'Consulting Model',
                'verbose_name_plural': 'Consulting Models',
            },
        ),
        migrations.CreateModel(
            name='ConsultingUnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('content', models.TextField(blank=True, null=True)),
                ('consulting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultingunits', to='magali_app.consultingmodel')),
            ],
            options={
                'verbose_name': 'Consulting Unit',
                'verbose_name_plural': 'Consulting Units',
            },
        ),
    ]
