# Generated by Django 4.2.1 on 2023-06-20 20:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magali_app', '0005_consultingunitmodel_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultingmodel',
            name='content',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultingunitmodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ctcategorymodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
